### ISSUE TITLE
unrecognized selector

### ISSUE THREAD

**Issue by EdwinCXD** [kukumaluCN/JXTAlertManager#1]
项目中尝试使用这个封装类
仅使用了viewController
提示错误
unrecognized selector sent to instance

**Comment by kukumaluCN** [comment]
你好，能具体定位到代码吗，以及使用方式

**Comment by EdwinCXD** [comment]
只导入了demo中的JXTAlertViewController，然后#import "JXTAlertController.h"
使用demo中的调用方法 报unrecognized selector sent to instance错误 
好像是UIViewController的JXTAlertController分类不识别
是需要配置哪边吗
￼

**Comment by kukumaluCN** [comment]
我试了一下，xcode9新建的空白项目，直接引入JXTAlertController的h/m文件，在vc中引入头文件，在`- (void)touchesBegan:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event`中触发方法。
```
- (void)touchesBegan:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event
{
    [self jxt_showAlertWithTitle:@"title" message:@"message" appearanceProcess:^(JXTAlertController * _Nonnull alertMaker) {
        alertMaker.
        addActionCancelTitle(@"cancel").
        addActionDestructiveTitle(@"按钮1");
    } actionsBlock:^(NSInteger buttonIndex, UIAlertAction * _Nonnull action, JXTAlertController * _Nonnull alertSelf) {
        if (buttonIndex == 0) {
            NSLog(@"cancel");
        }
        else if (buttonIndex == 1) {
            NSLog(@"按钮1");
        }
        NSLog(@"%@--%@", action.title, action);
    }];
}
```
一切正常的。
不知道你是否还有别的特殊操作？

**Comment by EdwinCXD** [comment]
我这刚也尝试了一样的方式 但是报一样的错误 你的邮箱多少 我把我这新建的工程发给你

**Comment by EdwinCXD** [comment]
解决了 是我这边Xcode工程配置问题 没有关联target
多谢您的答复

**Comment by kukumaluCN** [comment]
客气，感谢使用和反馈。
